### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by TuxNuX** [Lewdninja/liveme-pro-tools#92]
everything worked fine, I shut down "liveme pro tools"  I'm going to watch tv and when I come back
again having login problem

![screenshot_20180517_152831](https://user-images.githubusercontent.com/17123357/40274220-8eb9dc14-5bd1-11e8-92fb-211da939ff6e.png)

the login works well on the website

**Comment by TuxNuX** [comment]
again work well :)

I'm going to sleep, I'm tired to be 03:42 in France
goodbye people

**Comment by GumiG** [comment]
look into ur email and search if ur account is activated. also u have to use the same login @website and @livemeprotools (its somehow connected)

**Comment by TuxNuX** [comment]
@GumiG my email be validated for a long time, it work well on android and the website
![screenshot_20180520_134047](https://user-images.githubusercontent.com/17123357/40278700-565393a0-5c36-11e8-9a72-d3e8696ec337.png)

**Comment by ddpk** [comment]
FYI: You can close your own issues instead of making Lewdninja do it. It's to the left of the green "Comment" button when you scroll down to the comment box.

**Comment by stevvie** [comment]
Just started getting the SAME issue here

**Comment by dasheron** [comment]
Yeah, login not working for me either. Using mac and latest app version.

**Comment by ddpk** [comment]
Well our developer doesn't have a Mac so it's untested on Mac. Assuming it's not that easy for him to figure out why it's not working either. Seriously though, why is everyone on a Mac? Windows is cheaper and better

**Comment by izmore** [comment]
Same issue. I even tried to start a new email and matching liveme account. Same problem. I authenticated my email and everything. This keeps happening, is it something i'm doing wrong? I love the program but each time I get it running, it only seems to stay working for a day or so.

**Comment by Johnlourence** [comment]
Not letting me login either. The update worked awesome up until now. :(

**Comment by SawYouFriday** [comment]
On windows, I found if I erase the settings.json file and it forces me to re-enter the login info, it fixes the problem temporarily. You don't have to lose your bookmarks or anything. I'm not sure where the path is on the mac version. Probably in ~/library/application-support/ or something..

on windows in AppData/Roaming/liveme-pro-tools

Maybe a bug in the authenticating routine? Same login info can both work and not work. It sometimes seems like it doesn't try to log you in.

**Comment by Johnlourence** [comment]
Thanks, seems to works now.

**Comment by oledcrt** [comment]
I don't know about you Mac users but after deleting the json file failed to work I figured out it just needed to be allowed through Windows Firewall.  I'm not sure why that wasn't necessary before but for some reason it is now.

**Comment by SawYouFriday** [comment]
izmore - if you are using windows you will have to figure out how to show hidden folders. You need to go to c:\users\*yourusername*\AppData\Roaming\liveme-pro-tools

Here there will be a file named 'settings.json'. If you delete this file or rename it, the next time you run LMPT the username and password you use will have to be entered again. This seems to trigger it to authenticate again. I'm sure there is a fix possible for this.

On mac you have to open finder, go to the 'Go' menu at the top. Hold down the option key on the keyboard and 'Library' will show up in the list of destinations. Then go to the 'Appplication Support' folder and find liveme-pro-tools folder there. Same thing, remove the settings.json file.

Your bookmarks and other data will be safe. Just your window positions and main options (and login info) will be reset.

Hope that helps.

**Comment by izmore** [comment]
Dude! Thank you so much for the extra help, it’s now running! Much appreciated

Sent from my iPhone

On May 21, 2018, at 9:32 PM, SawYouFriday <notifications@github.com<mailto:notifications@github.com>> wrote:


izmore - if you are using windows you will have to figure out how to show hidden folders. You need to go to c:\users*yourusername*\AppData\Roaming\liveme-pro-tools

Here there will be a file named 'settings.json'. If you delete this file or rename it, the next time you run LMPT the username and password you use will have to be entered again. This seems to trigger it to authenticate again. I'm sure there is a fix possible for this.

On mac you have to open finder, go to the 'Go' menu at the top. Hold down the option key on the keyboard and 'Library' will show up in the list of destinations. Then go to the 'Appplication Support' folder and find liveme-pro-tools folder there. Same thing, remove the settings.json file.

Your bookmarks and other data will be safe. Just your window positions and main options (and login info) will be reset.

Hope that helps.

**Comment by mhags33** [comment]
i am not able to login, I have a login that works but wont let me authenticate through the liveme tools.  what if you signed up with your cell .  phone number, is that part of the issue?   its making me put in an email, which I have "connected" to my liveme account, but its still not letting me see replays, can anyone help?

**Comment by Xqqz** [comment]
@mhags33 
1: create a Gmail
2: Register and authenticate on Live.me with that gmail
3: Use that gmail to log-in on LiveMe Pro Tools

that's a 5-minute fix.

**Comment by mhags33** [comment]
Xqqz - thanks, I did that but its still not loggin me into the livemtools   its really becoming very annoying, my email is authenticated, and the Liveme password is not working, so I don't know if there is another password I need to use, but its giving me the error still.  really pissing me off now

**Comment by mhags33** [comment]
cant figure out why I cant see the replays still even after the email was verified for my liveme acct...

**Comment by Xqqz** [comment]
@mhags33  , make sure that the email you use on LMPT settings, is NOT the same email you are logged into Live.me App with

Live.me/Liveme.com does not allow a user to be logged in from 2 devices at the same time.

Log out of Live.me APP

Log into LMPT , give it a few seconds/minute to populate
and it should now be working.

Then on the App, log in with your OTHER email/method you used.
Make sure its NOT the same email that's in your LMPT settings.... i guarantee that's what the problem was.

**Comment by mhags33** [comment]
still not working, I went in and connected to another account, so I don't know what the hell the problem is.  do I need to be in one first with one account?  then go in with the connected account?  this is now confusing me...shouldn't be this complicated lol

**Comment by mhags33** [comment]
maybe I am not doing something right when entering on LMPT, I don't see an enter button or anything, should I see something like that?

**Comment by mhags33** [comment]
i have not gotten the new LMPT to work, the prior originally Liveme tools worked fine for me.  so i created an account, i actually have 2, one with my phone other with a different email, so i just need to know how to enter into LMPT and make sure its been verified
